import { Notification, app } from 'electron'
import { join } from 'path'

//Ignoring any errors generated by Compiler as this package doesn't come with types
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import Player from 'node-wav-player'

const PATH = process.env.NODE_ENV == 'development'
    ? join(app.getAppPath(), '..', `src/static/sounds`)
    : `${process.resourcesPath}\\sounds`

interface Options {
    title: string;
    body: string;
    type?: string;
}

export default function (options: Options) {
    const N = new Notification({
        title: options.title,
        body: options.body,
    })

    N.show()

    if (options.type)
        Player.play({ path: `${PATH}\\${options.type}.wav` })
}